version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - "54321:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: ["bash", "docker/app/start.sh"]
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    expose:
      - "8000"
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - app

volumes:
  pg-data:
