# Generated by Django 5.0.2 on 2024-02-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('priority', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('title', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True, null=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.executor')),
            ],
            options={
                'ordering': ['-priority', 'created'],
            },
        ),
    ]
